export const mockUsers = [
  {
    id: "user_1",
    name: "Dr. Alice Quantum",
    email: "alice.quantum@example.com",
    plan: "premium",
    status: "active",
    jobsSubmitted: 145,
    lastLogin: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 90).toISOString(),
  },
  {
    id: "user_2",
    name: "Bob Einstein",
    email: "bob.einstein@example.com",
    plan: "premium",
    status: "active",
    jobsSubmitted: 287,
    lastLogin: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 120).toISOString(),
  },
  {
    id: "user_3",
    name: "Carol Feynman",
    email: "carol.feynman@example.com",
    plan: "standard",
    status: "active",
    jobsSubmitted: 89,
    lastLogin: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 60).toISOString(),
  },
  {
    id: "user_4",
    name: "David Heisenberg",
    email: "david.h@example.com",
    plan: "standard",
    status: "active",
    jobsSubmitted: 52,
    lastLogin: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 45).toISOString(),
  },
  {
    id: "user_5",
    name: "Emma Schrödinger",
    email: "emma.s@example.com",
    plan: "free",
    status: "active",
    jobsSubmitted: 23,
    lastLogin: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 15).toISOString(),
  },
  {
    id: "user_6",
    name: "Frank Dirac",
    email: "frank.dirac@example.com",
    plan: "premium",
    status: "active",
    jobsSubmitted: 198,
    lastLogin: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 150).toISOString(),
  },
  {
    id: "user_7",
    name: "Grace Bohr",
    email: "grace.bohr@example.com",
    plan: "free",
    status: "inactive",
    jobsSubmitted: 8,
    lastLogin: new Date(Date.now() - 1000 * 60 * 60 * 24 * 30).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 35).toISOString(),
  },
  {
    id: "user_8",
    name: "Henry Planck",
    email: "henry.p@example.com",
    plan: "standard",
    status: "active",
    jobsSubmitted: 134,
    lastLogin: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 75).toISOString(),
  },
];

export const mockPricingPlans = [
  {
    id: "plan_free",
    name: "Free",
    description: "Perfect for getting started with quantum computing",
    monthlyPrice: 0,
    yearlyPrice: 0,
    status: "published",
    isPopular: false,
    features: [
      "5 quantum jobs per month",
      "Access to 5-qubit simulators",
      "Community support",
      "Basic tutorials and documentation",
      "Limited circuit depth"
    ],
    subscribers: 1234,
    revenue: 0,
  },
  {
    id: "plan_standard",
    name: "Standard",
    description: "For researchers and students exploring quantum algorithms",
    monthlyPrice: 2900,
    yearlyPrice: 29900,
    status: "published",
    isPopular: true,
    features: [
      "100 quantum jobs per month",
      "Access to 15-qubit simulators",
      "Priority email support",
      "Advanced tutorials and courses",
      "Extended circuit depth",
      "Job result history (90 days)"
    ],
    subscribers: 567,
    revenue: 164300,
  },
  {
    id: "plan_premium",
    name: "Premium",
    description: "For professionals and teams running production workloads",
    monthlyPrice: 9900,
    yearlyPrice: 99900,
    status: "published",
    isPopular: false,
    features: [
      "Unlimited quantum jobs",
      "Access to 127-qubit real quantum hardware",
      "24/7 dedicated support",
      "Custom algorithm consulting",
      "Team collaboration features",
      "Unlimited job result history",
      "API access with higher rate limits",
      "Early access to new features"
    ],
    subscribers: 234,
    revenue: 231660,
  },
  {
    id: "plan_enterprise",
    name: "Enterprise",
    description: "Custom solutions for large organizations",
    monthlyPrice: 29900,
    yearlyPrice: 299900,
    status: "draft",
    isPopular: false,
    features: [
      "Everything in Premium",
      "Dedicated quantum hardware allocation",
      "On-premise deployment options",
      "Custom SLAs and guarantees",
      "Private cloud instances",
      "Dedicated account manager",
      "Custom integrations",
      "Training and workshops"
    ],
    subscribers: 0,
    revenue: 0,
  },
];

export const mockContentSections = [
  {
    id: "content_hero",
    type: "hero",
    title: "Hero Section - Main Landing Page",
    content: "Experience the Future of Computing in the Cloud. Run, learn, and innovate with powerful quantum systems accessible anywhere. Join the quantum revolution today.",
    status: "published",
    version: 3,
    publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 7).toISOString(),
    updatedBy: "admin_alice",
  },
  {
    id: "content_features",
    type: "features",
    title: "Features Section",
    content: "Our platform offers quantum simulators, real hardware access, comprehensive learning resources, and enterprise-grade security. Build quantum applications with ease.",
    status: "published",
    version: 5,
    publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 14).toISOString(),
    updatedBy: "admin_bob",
  },
  {
    id: "content_faq",
    type: "faq",
    title: "FAQ Section",
    content: "Frequently asked questions about quantum computing, pricing, hardware access, and platform features. Over 50 common questions answered.",
    status: "published",
    version: 2,
    publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 21).toISOString(),
    updatedBy: "admin_alice",
  },
  {
    id: "content_getting_started",
    type: "docs_page",
    title: "Getting Started Guide",
    content: "A comprehensive guide to getting started with QuantumCloud. Learn how to create your first quantum circuit, submit jobs, and interpret results.",
    status: "draft",
    version: 1,
    publishedAt: null,
    updatedBy: "admin_carol",
  },
];

export const mockNews = [
  {
    id: "news_1",
    title: "New 127-Qubit Quantum Processor Now Available",
    body: "We're excited to announce access to our latest quantum processor with 127 qubits. Premium users can now run experiments on cutting-edge quantum hardware with improved coherence times and gate fidelities.",
    status: "published",
    visibility: "all_users",
    isPinned: true,
    publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
    impressions: 2847,
    clicks: 423,
  },
  {
    id: "news_2",
    title: "Scheduled Maintenance - Saturday, 2AM-4AM EST",
    body: "Our platform will undergo scheduled maintenance this Saturday from 2AM to 4AM EST. During this time, job submissions will be temporarily unavailable. All running jobs will be safely preserved.",
    status: "published",
    visibility: "all_users",
    isPinned: true,
    publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 1).toISOString(),
    impressions: 1523,
    clicks: 187,
  },
  {
    id: "news_3",
    title: "Quantum Algorithm Workshop - Register Now",
    body: "Join our free workshop on quantum algorithms next month. Learn from industry experts about Shor's algorithm, Grover's search, and quantum machine learning. Limited seats available.",
    status: "published",
    visibility: "premium_users",
    isPinned: false,
    publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(),
    impressions: 892,
    clicks: 156,
  },
  {
    id: "news_4",
    title: "API Rate Limits Increased for All Users",
    body: "Good news! We've increased API rate limits across all plans. Free users now get 100 requests/hour, Standard users get 1000 requests/hour, and Premium users get unlimited requests.",
    status: "draft",
    visibility: "all_users",
    isPinned: false,
    publishedAt: null,
    impressions: 0,
    clicks: 0,
  },
];

export const mockLeaderboard = [
  {
    id: "score_1",
    userId: "user_1",
    userName: "Dr. Alice Quantum",
    gameType: "quantum_quest",
    score: 9850,
    level: 42,
    achievedAt: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
  },
  {
    id: "score_2",
    userId: "user_2",
    userName: "Bob Einstein",
    gameType: "entanglement_challenge",
    score: 9234,
    level: 38,
    achievedAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
  },
  {
    id: "score_3",
    userId: "user_6",
    userName: "Frank Dirac",
    gameType: "quantum_quest",
    score: 8876,
    level: 35,
    achievedAt: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
  },
  {
    id: "score_4",
    userId: "user_8",
    userName: "Henry Planck",
    gameType: "circuit_builder",
    score: 7923,
    level: 31,
    achievedAt: new Date(Date.now() - 1000 * 60 * 60 * 72).toISOString(),
  },
  {
    id: "score_5",
    userId: "user_3",
    userName: "Carol Feynman",
    gameType: "quantum_quest",
    score: 7456,
    level: 29,
    achievedAt: new Date(Date.now() - 1000 * 60 * 60 * 96).toISOString(),
  },
  {
    id: "score_6",
    userId: "user_4",
    userName: "David Heisenberg",
    gameType: "entanglement_challenge",
    score: 6892,
    level: 26,
    achievedAt: new Date(Date.now() - 1000 * 60 * 60 * 120).toISOString(),
  },
  {
    id: "score_7",
    userId: "user_5",
    userName: "Emma Schrödinger",
    gameType: "circuit_builder",
    score: 5623,
    level: 22,
    achievedAt: new Date(Date.now() - 1000 * 60 * 60 * 144).toISOString(),
  },
];

export const mockAuditLogs = [
  {
    id: "log_1",
    adminUserId: "admin_alice",
    adminName: "Alice Admin",
    action: "update",
    entityType: "pricing_plan",
    entityId: "plan_standard",
    changes: { monthlyPrice: { from: 2500, to: 2900 } },
    ipAddress: "192.168.1.100",
    createdAt: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
  },
  {
    id: "log_2",
    adminUserId: "admin_bob",
    adminName: "Bob Admin",
    action: "publish",
    entityType: "news",
    entityId: "news_1",
    changes: { status: { from: "draft", to: "published" } },
    ipAddress: "192.168.1.101",
    createdAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
  },
  {
    id: "log_3",
    adminUserId: "admin_alice",
    adminName: "Alice Admin",
    action: "create",
    entityType: "user",
    entityId: "user_8",
    changes: { plan: "standard", status: "active" },
    ipAddress: "192.168.1.100",
    createdAt: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
  },
  {
    id: "log_4",
    adminUserId: "admin_carol",
    adminName: "Carol Admin",
    action: "update",
    entityType: "content",
    entityId: "content_hero",
    changes: { version: { from: 2, to: 3 } },
    ipAddress: "192.168.1.102",
    createdAt: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
  },
  {
    id: "log_5",
    adminUserId: "admin_bob",
    adminName: "Bob Admin",
    action: "delete",
    entityType: "news",
    entityId: "news_old_1",
    changes: null,
    ipAddress: "192.168.1.101",
    createdAt: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
  },
];

export const mockAnalytics = {
  activeProjects: 3456,
  avgGameScore: 4250,
  totalRevenue: 395960,
  userGrowthData: [
    { month: "May", signups: 245, churn: 12 },
    { month: "Jun", signups: 312, churn: 18 },
    { month: "Jul", signups: 428, churn: 22 },
    { month: "Aug", signups: 567, churn: 31 },
    { month: "Sep", signups: 692, churn: 28 },
    { month: "Oct", signups: 823, churn: 35 },
  ],
  usersByPlan: [
    { name: "Free", value: 1234, fill: "#3b82f6" },
    { name: "Standard", value: 567, fill: "#10b981" },
    { name: "Premium", value: 234, fill: "#f59e0b" },
  ],
  revenueByMonth: [
    { month: "May", revenue: 52400 },
    { month: "Jun", revenue: 68200 },
    { month: "Jul", revenue: 89500 },
    { month: "Aug", revenue: 123800 },
    { month: "Sep", revenue: 187600 },
    { month: "Oct", revenue: 231660 },
  ],
  jobsByStatus: [
    { status: "Completed", count: 8234, fill: "#10b981" },
    { status: "Running", count: 145, fill: "#3b82f6" },
    { status: "Queued", count: 89, fill: "#f59e0b" },
    { status: "Failed", count: 234, fill: "#ef4444" },
  ],
};

export const mockUserStats = {
  totalUsers: 2035,
  premiumUsers: 234,
  standardUsers: 567,
  freeUsers: 1234,
  newUsersLast7Days: 45,
  newUsersLast30Days: 187,
  activeUsersLast24h: 892,
  userRetentionRate: 87.5,
};
